name: SpecFlow Test Run
on:
  push:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - uses:  ./
      with:
        test-assembly-path: SpecFlow.Poc/bin/Release/net6.0
        test-assembly-dll: SpecFlow.Poc.dll
        output-html: LivingDoc.html
        framework: net6.0
